pipeline:
  build_mirror:
    image: denoland/deno
    commands:
      - apt update
      - apt install make
      - deno --version
      - make
    when:
      branch: [main]
  deploy_mirror:
    image: rclone/rclone
    commands:
      - "rclone sync dist/ :sftp:/ --sftp-host frontier.gwei.cz --sftp-user atscan-ecosystem-deploy --sftp-port 2022 --sftp-pass $RCLONE_PASS -v"
    secrets: [RCLONE_PASS]
    when:
      event: push
      branch: [main]
branches: [main]