name: Test, build, deploy 

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Prague"

      - name: Build sources
        run: make

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist